name: 'Master/Main Branch (Deploy)'

on: [push]

jobs:

## commented out due to inordinate time needed to run
  # qa:
  #   name: SuperLinter
  #   if: always()
  #   runs-on: ubuntu-latest
  #   env:
  #     RUN_LOCAL: true
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: github/super-linter@v3.13.2

  validate_cfn-nag:
    runs-on: ubuntu-latest
    if: always()
    steps:
    - uses: actions/checkout@v2
    - uses: grolston/cfn-security@all-tools
      with:
        cloudformation_directory: "./cloudformation/"
        scanner: "cfn-nag"

  ## cfn-guard security scan
  security-scan-cfn-guard:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: grolston/cfn-security@all-tools
      with:
        cloudformation_directory: './cloudformation/' ## change to your template directory
        scanner: "cfn-guard"

  ## checkov security scan
  validate_checkov:
    runs-on: ubuntu-latest
    if: always()
    steps:
    - uses: actions/checkout@v2
    - uses: grolston/cfn-security@all-tools
      with:
        cloudformation_directory: "./cloudformation/"
        scanner: "checkov"
