name: 'Checkov and Nag Actions'

on: [push]

jobs:
  checkov-job:
    runs-on: ubuntu-latest
    name: checkov-action
    steps:
      - name: Checkout repo
        uses: actions/checkout@master

      - name: Run Checkov action
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: cloudformation/

  cfn-nag-job:
    runs-on: ubuntu-latest
    name: cfn-nag-action
    steps:
      - name: Checkout repo
        uses: actions/checkout@master

      - name: cfn-nag
        uses: stelligent/cfn_nag@master
        with:
          input_path: cloudformation/